export default [
  'authTokenVersion',
  'blackListedAt',
  'confirmed',
  'confirmTokenVersion',
  'email',
  'emailTokenVersion',
  'facebookId',
  'googleId',
  'hash',
  'isBlackListed',
  'resetPasswordTokenVersion',
  'salt',
  'updatedAt',
  'updatedEmailTokenVersion',
];
